name: Approve

on:
  pull_request:
    branches:
      - main
      - master
      
jobs:
  approve:
    name: Approve PR when it only contains image version bumps
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Verify that PR only contains image version bumps
      run: ./verify-approval.sh
    - name: Approve pull request
      uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
